Repository juice-shop/pwning-juice-shop, pull requests merged in 2019-06, with the labels that each got.

#38 Spell corrections
  appendix/solutions.md
  part1/categories.md
  part1/ctf.md
  part1/customization.md
  part1/happy-path.md
  part1/running.md
  part2/README.md
  part2/broken-access-control.md
  part2/security-misconfiguration.md
  part2/xss.md
  part2/xxe.md
  part3/codebase.md
  part3/contribution.md
Labels: size/M

#36 Polution -> Pollution
  appendix/solutions.md
Labels: size/XS

#39 Added Hints/Solution to Chris' erased user account
  appendix/solutions.md
  part2/broken-authentication.md
Labels: size/S
